name: Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install latest Clang/LLVM
        run: |
          sudo apt-get update
          sudo apt-get install -y wget lsb-release software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
          clang --version
          clang++ --version

      - name: Build
        run: |
          CC=clang CXX=clang++ make
          mkdir -p build_out
          cp ./gtn build_out/

      - name: Upload to Github Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: build_out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
